// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv



import { defineConfig } from "prisma/config";
import { PrismaNeon } from "@prisma/adapter-neon";

export default defineConfig({
  earlyAccess: true,
  schema: "prisma/schema.prisma",
  migrate: {
    adapter: () => {
      const adapter = new PrismaNeon({
        connectionString: process.env.DATABASE_URL!,
      });
      return adapter;
    },
  },
});